services:
  mysql:
    image: mysql:8.1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grades_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  analytics:
    build: ./analytics
    container_name: analytics_service
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=grades_db
      - MONGO_HOST=mongo
    ports:
      - "5003:5003"
    depends_on:
      - mysql
      - mongo

volumes:
  mysql_data:
  mongo_data: