apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  JWT_SECRET: secretkey
  FLASK_SECRET_KEY: secretkey

  MYSQL_HOST: mysql
  MYSQL_USER: user1
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: rootpassword
  MYSQL_DATABASE: grades_db

  MONGO_HOST: mongo
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: mongopass
  MONGO_INITDB_DATABASE: results_db
  MONGO_USER: user2
  MONGO_PASSWORD: user2pass

